name: Run Claude Agent on Dependabot Issues

on:
  issues:
    types: [opened]

jobs:
  run-claude-agent:
    # Only run on issues created by your Dependabot->Issue workflow
    if: contains(github.event.issue.title, '[dependabot]')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests anthropic PyGithub

      - name: Run Claude agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.repository }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          python scripts/run_claude_agent.py \
            --issue_number "$ISSUE_NUMBER" \
            --repo "$REPO_NAME" \
            --github_token "$GITHUB_TOKEN" \
            --claude_api_key "$CLAUDE_API_KEY"